name: "Pull Request: Validate"

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.head_ref }}-pr-validate
  # cancel-in-progress: true

jobs:
  pr-metadata:
    uses: k8s-at-home/charts/.github/workflows/pr-get-metadata.yaml@master

  charts-readme:
    uses: k8s-at-home/charts/.github/workflows/charts-update-readme.yaml@master
    needs:
      - pr-metadata
    with:
      isRenovatePR: ${{ needs.pr-metadata.outputs.isRenovatePR }}
      modifiedCharts: ${{ needs.pr-metadata.outputs.addedOrModifiedCharts }}

  charts-lint:
    uses: k8s-at-home/charts/.github/workflows/charts-lint.yaml@master
    needs:
      - pr-metadata
      - charts-readme
    with:
      checkoutCommit: ${{ needs.charts-readme.outputs.commitHash }}
      modifiedCharts: ${{ needs.pr-metadata.outputs.addedOrModifiedCharts }}
